Feat/create listing
jadeallencook/communalists pull request #12
Opened 2022-11-26 03:57 UTC by asbhaskar

2022-12-19 05:46 UTC, claytonleonardcook requested changes

2022-12-19 05:46 UTC, claytonleonardcook commented on src/components/organisms/CreateListingForm/index.tsx
> +			})
I would rewrite this as a ternary:
```ts
const newAttributes: [string, string][] = inputs.attributes.map((attributeArray) => {
     return attributeArray[0] === name ? [name,value] : attributeArray;
})
```

2022-12-19 05:46 UTC, claytonleonardcook commented on src/components/organisms/CreateListingForm/index.tsx
> +				{formErrors.location ? (<p className="is-danger">{formErrors.location}</p>) : null}
Could this not be a `&&` instead of a ternary?

```ts
{formErrors.location && (<p className="is-danger">{formErrors.location}</p>) }
```

It might also be possible to use the CSS [empty pseudo selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:empty) to hide this.

I image you could do it either way you want though.

2022-12-19 05:46 UTC, claytonleonardcook commented on src/components/organisms/CreateListingForm/index.tsx
> +	const handleChange: React.ChangeEventHandler<any> = ({ target: { value, name, type } }): void => {
Is there anyway we could avoid using the `any` keyword?

2022-12-19 05:46 UTC, claytonleonardcook commented on src/utils/formUtils.ts
> +    errors.inner.forEach((err: any) => {
Same thing as above comment about avoiding `any` keyword.

2022-12-19 05:46 UTC, claytonleonardcook commented on src/utils/formUtils.ts
> +        if (err.path) validationErrors[err.path] = err.errors[0]
This could probably be collapsed to a single line, no `{}` brackets.
It could also possibly be turned into a ternary but I'm unsure how.
Or, you could avoid nesting the assignment in a if statement like this:

```ts
if(!err.path) continue;
validationErrors[err.path] = err.errors[0];
```

It's practically the same but I think it looks better. A lot of developers side with this kind of code style since it helps a ton on large functions with nested if statements.

2022-12-19 07:00 UTC, asbhaskar commented on src/components/organisms/CreateListingForm/index.tsx
> +				{formErrors.location ? (<p className="is-danger">{formErrors.location}</p>) : null}
This is just taken from the [Formik docs](https://formik.org/docs/guides/validation), I don't feel strongly either way but Jade seems to favor ternarys in other parts of the codebase so I figured I'd keep it consistent.

2022-12-19 07:02 UTC, asbhaskar commented on src/components/organisms/CreateListingForm/index.tsx
> +	const handleChange: React.ChangeEventHandler<any> = ({ target: { value, name, type } }): void => {
Yes, I just have to look into this some more, there's an issue I'm getting with some of the onChange events appearing to have type `FormControlElement` but that's not recognized by my linter.

2022-12-31 07:34 UTC, jadeallencook commented on src/components/organisms/CreateListingForm/index.tsx
> +				{formErrors.location ? (<p className="is-danger">{formErrors.location}</p>) : null}
I'd like to use the logical && operator when the fallback is null but a ternary when choosing between two components, I've went ahead and made this change.

2022-12-31 07:36 UTC, jadeallencook commented
LGTM

2022-12-31 07:38 UTC, jadeallencook approved these changes

2022-12-31 07:38 UTC, merged