Feat/create group
jadeallencook/communalists pull request #17
Opened 2022-11-30 05:20 UTC by asbhaskar

2022-12-01 00:02 UTC, jadeallencook requested changes
PTAL

2022-12-01 00:02 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/index.tsx
> +                                            ))}
We should create a utility for this, we will most likely use this logic in several places.

2022-12-01 00:02 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/initial-values.ts
> +const initialValues = {
There is a `GroupInterface`.

2022-12-01 00:42 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +            onSubmit={handleSubmit()}
I've changed `handleSubmit = () => (values: any) =>` to `handleSubmit = (values: any) =>` to accompany this change.

2022-12-01 00:46 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +	}, [shouldSubmit, setShouldSubmit])
It's an attempt at passing the state from parent to child to trigger a form submission from our discussion on slack. My experience with forms (and Formik) is limited so I wanted to get your feedback on it. Line 27 is a typo and should be under the button click.

2022-12-01 02:22 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +    const handleStateChange = (event) => {
Resolved in a zoom call, we're now using: 
const handleStateChange: React.ChangeEventHandler<HTMLSelectElement> = ({ target: { value } }) => {

2022-12-01 02:23 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +	}, [shouldSubmit, setShouldSubmit])
Resolved in a zoom call: We are going to try moving the submit buttons inside the Form component for now. Need to think about this further in the case of using forms outside of modals

2022-12-01 06:09 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/style.ts
> +    },
Can I move all input related css (and the renderError function css from above) throughout the codebase to `theme.css`? Some of the styledComponent values seem to be overriding the global selectors.

2022-12-01 06:23 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/initial-values.ts
> +const initialValues = {
Can we change `phone: number` in `GroupInterface` to a string for both the inclusion of country codes and easier use with setting default values in forms?

2022-12-02 05:53 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/index.tsx
> +    const [stateKey, setStateKey] = useState("CA")
It was trying to pull from @react/types.

I made a few updates and pushed them to your branch @asbhaskar. 

You can access those types at @custom-types/ now.

2022-12-02 05:55 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/initial-values.ts
> +const initialValues = {
SGTM.

2022-12-02 05:55 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/style.ts
> +    },
What if we created out own inputs in @atom? 

It would give us more control.

2022-12-03 00:20 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/style.ts
> +    },
This is definitely something we could discuss doing if we need that extra control for future components. The issue I mentioned was just related to the css hierarchy (I think styledComponents renders styles inline?). Like how the styles in `CreateAccountForm/styles.ts` seem to override `theme.css` when we look at its inputs

2022-12-03 00:22 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/initial-values.ts
> +const initialValues = {
I made this change for zip codes too. I just learned that they can start with leading 0s so strings seem to make more sense.

2022-12-03 16:36 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +    isModal: boolean,
For now, I've tried to merge form functionality in and out of modals using this boolean value that will be passed in from the parent (default is false). Let me know if you think of a better way to handle this.

2022-12-03 16:36 UTC, asbhaskar commented on src/theme.css
> +}
Input styles have been made global, corresponding css in styledComponents have been temporarily commented out. Let me know if this is preferable.

2022-12-03 16:36 UTC, asbhaskar commented on src/utils/formUtils.tsx
> +}
These are temporary utils, the issue we have on the create group form is that we would use `formOptionMapValueByValues` where most other components would use the other `formOptionMapValueByKeys` due to how some of the data/interfaces are set. I've made two separate functions here for now. I'll fix the parameter type later today.

Please let me know if you know a better way to structure this (and name it based on the structure)

2022-12-03 16:36 UTC, asbhaskar commented on interfaces/address.ts
> +	zipcode: string;
As per my previous comment on your review @jadeallencook I've made zipcode a string since they can have leading zeros.

2022-12-03 16:36 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +}: CreateGroupFormInterface) => {
I've taken out styledComponents from this component as with the changes to input styling in `theme.css` there was currently no need for it.

2022-12-03 21:30 UTC, jadeallencook requested changes
Looking good, just a few comments.

2022-12-03 21:30 UTC, jadeallencook commented on src/components/atoms/RenderError/index.tsx
> +export default renderError
Please capitalize component names `RenderError`.

Also, what do you think about this?

```tsx
const FormError = ({children}) => <p className="help is-danger">{children}</p>;
```

2022-12-03 21:30 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/index.tsx
> +                values,
Will you deconstruct values here?

```ts
{ name, bio, website, phone, email, address: { street, city, zipcode } }
```

2022-12-03 21:30 UTC, jadeallencook commented on src/components/atoms/RenderError/index.tsx
> +export default renderError
Or is this specific to Formik?

2022-12-03 21:30 UTC, jadeallencook commented on src/components/organisms/EditProfileForm/style.ts
> +	// },
Please remove these commented lines.

2022-12-03 21:30 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/index.tsx
> +                            </Modal.Footer>}
Use a ternary here:

```tsx
{ !isModal ? <Button /> : <Footer /> }
```

2022-12-03 21:30 UTC, jadeallencook commented on src/theme.css
> +}
I think it might be best to use classes here. 

```css
input.form {}
input.form.small {}

/* or */

input.form {}
input.form_small {}
```

That way we don't affect any other inputs outside of forms.

2022-12-03 21:30 UTC, jadeallencook commented on src/utils/formUtils.tsx
> +}
This makes sense but I'd remove the JSX from here and make it a TS file. 

Utilities typically do some type of data manipulation and return the newly formatted data. 

```ts
import locationMap from '@objects/location-map';

export const getLocationKeysByState = (state: USState) => 
    Object.entries(locationMap[state]).map(([key, value]) => value);
```

Then you can use Jest to write a unit test.

2022-12-03 21:30 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/index.tsx
> +import { formOptionMapValueByValues } from '../../../utils/formUtils';
Please add a `@utilities` alias.

2022-12-03 21:30 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/index.tsx
> +    isModal: boolean,
Good idea, this works for now!

2022-12-03 21:56 UTC, asbhaskar commented on src/components/atoms/RenderError/index.tsx
> +export default renderError
So Formik has an `<ErrorMessage>` component that gets used like this:
`<ErrorMessage name="name" render={RenderError} />`
I think the types are defined by the ErrorMessage component - if I try to replace the current function with your destructuring, I get a typeError that seems to require `(message: string)`.

I was a bit iffy on treating RenderError as a component because it really does not seem to have much utility outside of being passed as a function into Formik Errors but I'll look into this tonight.

2022-12-03 22:04 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +                values,
I'm sure its an issue on my end but I'm having trouble with this. I'm getting a couple different errors if I try anything like this

I'm trying to find out if it's common practice to destructure these and if there are any examples online but no luck yet.

2022-12-03 22:53 UTC, asbhaskar commented on src/utils/formUtils.tsx
> +}
Besides readability, is there a benefit to extracting the `Object.entries` map to a utils file for use in this form? We would have to map over the resulting array from `getLocationKeyByState` to create `<option />` nodes in the tsx file anyways, and for other forms we would need to create an array `[{key: 'key', value: 'value'}]` which `Object.entries` already does.

2022-12-03 23:20 UTC, asbhaskar commented on src/utils/formUtils.tsx
> +}
I'm adding this btw: 

> export const getLocationKeysAndValuesByState = (state: USStateType) => 
    Object.entries(locationMap[state]).map(([key, value]) => {return {key, value} as {key: string, value: string}})

2022-12-04 02:02 UTC, jadeallencook commented on src/utils/formUtils.tsx
> +}
LGTM, it makes this code easier to test and it's generic to enough to be used in multiple cases. 

You could create a React component that utilizes this in `@organisms/StateOptions`. 

I'm sure we'll need that select input in a few other places as well.

2022-12-04 02:06 UTC, jadeallencook commented on src/components/atoms/RenderError/index.tsx
> +export default renderError
Let's get this merged in and then revisit this. 

Maybe we should create our own form component that we can pass and object to. 

That way we can reduce the footprint and make it easier to maintain.

2022-12-04 02:07 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/index.tsx
> +                values,
Have you replaces that line with this?

```ts
values: { name, bio, website, phone, email, address: { street, city, zipcode } },
```

2022-12-04 03:04 UTC, asbhaskar commented on src/utils/formUtils.tsx
> +}
That's a good idea, I'll try to get this pushed, standardize the types on the other forms then try to play around with this.

2022-12-04 03:05 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +                values,
No, but it works and in hindsight makes a lot more sense than what I was trying lol

2022-12-04 03:34 UTC, asbhaskar reviewed
I've reverted the changes I made to input styling in `styles.ts` for most of the forms. I figured it would be cleaner to open another 'fix' branch after this gets merged and use createGroupForm as a template to standardize the other form components.

2022-12-11 08:12 UTC, jadeallencook requested changes
LGTM, just a couple comments.

2022-12-11 08:12 UTC, jadeallencook commented on src/utils/index.ts
> +export { getLocationKeysAndValuesByState } from './formUtils';
I'm thinking we should stay away from index files like this. There's a couple other ones in the project that I'd like to phase out. I'd like to not have the responsibility of remembering to maintain them.

2022-12-11 08:12 UTC, jadeallencook commented on src/components/organisms/CreateGroupForm/index.tsx
> +                                <Button variant="secondary" onClick={() => handleClose()}>
```jsx
<Button variant="secondary" onClick={handleClose}>
```

2022-12-11 17:01 UTC, asbhaskar commented on src/utils/index.ts
> +export { getLocationKeysAndValuesByState } from './formUtils';
sgtm

2022-12-11 17:04 UTC, asbhaskar commented on src/theme.css
> +}
sgtm

2022-12-11 17:05 UTC, asbhaskar commented on src/theme.css
> +}
sure, I'll switch the form and input classes around so its like ```form.standard-form input.input-sm```

2022-12-11 19:15 UTC, asbhaskar commented on src/components/organisms/CreateGroupForm/index.tsx
> +                                <Button variant="secondary" onClick={() => handleClose()}>
Nevermind, the issue can be bypassed by assigning type React.SetStateAction<any> to handleClose, made the change

2022-12-11 21:42 UTC, jadeallencook approved these changes
LGTM

2022-12-12 00:19 UTC, merged