Feat/refactor tooltip
jadeallencook/communalists pull request #40
Opened 2023-02-13 02:07 UTC by asbhaskar

@jadeallencook Can I get your thoughts on the structure of the Tooltip component? I'll add the missing types accordingly.

The image or other div comes in as a child but the tooltip text gets passed as a props div to allow rich styling.

2023-02-13 07:40 UTC, jadeallencook requested changes

2023-02-13 07:40 UTC, jadeallencook commented on src/components/Tooltip/index.tsx
> +			animationDelay: '1s',
Please make this a styled component, this was just a quick and dirty way to get it up and going that I'm trying to avoid in the future. Maybe we could pass an icon prop that defaults to the info icon as well

2023-02-13 07:40 UTC, jadeallencook commented on src/components/Tooltip/index.tsx
> +	children?: any
You can remove the `textDiv` prop and just use the children.

Children should not be optional the correct type is ```JSX.Element | string``` I believe.

2023-02-13 07:57 UTC, asbhaskar commented on src/components/Tooltip/index.tsx
> +	children?: any
Okay, I think I switched the text and icon props/children around. I was using children for the icon which is currently optional and defaults to the info icon. I can switch them and if needed I can make the icon prop take in jsx so we can display tooltips for things that aren't images in case we need that for some reason.

2023-02-16 05:06 UTC, asbhaskar commented
> Please make this a styled component, this was just a quick and dirty way to get it up and going that I'm trying to avoid in the future. Maybe we could pass an icon prop that defaults to the info icon as well

Are we going to use tooltips for buttons or anything that's not an icon? I implemented this thinking the answer was yes then realized this comment was referencing the default image object. 

If we are, I would add this css to a global style since we need to pass in a jsx object as the ```element``` prop. If not, we can get away with a src prop, alt prop and making this css a part of the parent styled component

2023-02-16 08:25 UTC, jadeallencook commented
This will only be for the icon @asbhaskar.

2023-02-18 19:23 UTC, asbhaskar commented
@jadeallencook Please ignore the rereview, I'll ping you on slack when it's ready.

2023-02-18 22:13 UTC, jadeallencook commented on src/components/RequestModal/index.tsx
> +                        // element={<img src={CalendarSVG} style={{ cursor: 'pointer' }} />}
Can you remove this comment please?

2023-02-18 22:13 UTC, jadeallencook commented on src/theme.css
> +}
Can this style not exist within the tooltip stylesheet?

2023-02-18 23:26 UTC, asbhaskar commented on src/theme.css
> +}
Moving this style into the `style.ts` that corresponds with the Tooltip breaks functionality for some reason. I'm not familiar with how our way of using Styled Components works, but I'm guessing it has something to do with the following:

<img width="1440" alt="Screen Shot 2023-02-18 at 3 06 06 PM" src="https://user-images.githubusercontent.com/18740303/219903396-99d32fb6-211f-49a7-ae7b-a466e5c037a5.png">

I don't know if there's an additional step I need to take or if something's being lost in the OverlayTrigger or if it's because the Tooltip renders under `<body>`, but I can't seem to get any styling on the Tooltip from `style.ts`. The style works inline though.

2023-02-19 00:04 UTC, jadeallencook commented on src/theme.css
> +}
You should be able to add this to your style:


```ts
'.tooltip-inner-container': {
    padding: '10px',
    textAlign: 'start'
}
```

2023-02-19 01:21 UTC, asbhaskar commented on src/theme.css
> +}
This is what I originally tried, I have removed the comment you mentioned above and committed this addition for reference

2023-02-19 01:35 UTC, asbhaskar commented on src/theme.css
> +}
@jadeallencook After doing some testing, it looks like styled components is prop drilling or something so the styles go from the parent `span` -> `OverlayTrigger` and try to apply to the child of `OverlayTrigger`, the Tooltip is in the `overlay` prop of `OverlayTrigger` so the styles can't find their way to the Tooltip.

2023-02-19 07:17 UTC, jadeallencook approved these changes

2023-02-19 07:18 UTC, merged