Feat/filters
jadeallencook/communalists pull request #41
Opened 2023-02-14 19:43 UTC by claytonleonardcook

2023-02-14 20:25 UTC, jadeallencook requested changes

2023-02-14 20:25 UTC, jadeallencook commented on src/api/get-requests.ts
> +            )
This should be a boolean.

2023-02-14 20:25 UTC, jadeallencook commented on src/api/get-requests.ts
> +        ];
Please deconstruct the filters on line 22.

```ts
const { location, language, stage, driver } = filters;
```

2023-02-14 20:25 UTC, jadeallencook commented on src/forms/FilterForm/index.tsx
> +                                <option value={''}>Location</option>
These default options need to be more clear, maybe "any location"?

2023-02-14 20:25 UTC, jadeallencook commented on src/forms/FilterForm/index.tsx
> +                        <Button size="sm" onClick={() => setRefetch(true)}>Apply Filters</Button>
This button doesn't take up full width on mobile.

2023-02-14 20:25 UTC, jadeallencook commented on src/pages/Dashboard.tsx
>          });
Triggering this should show the loader while it's being requested.

2023-02-14 20:25 UTC, jadeallencook commented on types/filters.ts
> +};
Shouldn't this be an interface?

2023-02-15 17:23 UTC, claytonleonardcook commented on src/api/get-requests.ts
> +            )
What should be a boolean? `filters.driver === 'assigned'` evaluates to a boolean. I opted for following the same structure as the other filters so it's straight forward to add ones later.

2023-02-15 17:27 UTC, claytonleonardcook commented on src/forms/FilterForm/index.tsx
> +                        <Button size="sm" onClick={() => setRefetch(true)}>Apply Filters</Button>
Should it? I think keeping it a smaller size breaks it up from the rest of the inputs.

2023-02-15 19:16 UTC, claytonleonardcook commented on src/pages/Dashboard.tsx
>          });
I don't understand what this comment is targeting.

2023-02-15 21:39 UTC, jadeallencook commented on src/api/get-requests.ts
> +            )
The other filters aren't booleans because their values are dynamic, the driver filter only has two possible values (true or false) and assigning it to a string makes the code more error-prone and harder to read. 

It's best to use the appropriate data type.

2023-02-15 21:44 UTC, jadeallencook commented on src/forms/FilterForm/index.tsx
> +                        <Button size="sm" onClick={() => setRefetch(true)}>Apply Filters</Button>
Yes, the other button are full width on mobile and the user is accustomed to seeing full-width buttons on mobile screens – plus it's the only primary action on the screen.

2023-02-15 21:46 UTC, jadeallencook commented on src/pages/Dashboard.tsx
>          });
You should display a loading spinner when the "apply filters" button is pressed and the request is being processed so the user knows that their request is being executed.

2023-02-16 04:12 UTC, claytonleonardcook commented on src/api/get-requests.ts
> +            )
I'm trying to follow the parallels that already exist with each input having a file within the objects folder. You cannot setup this input the same as the others because booleans cannot exist as keys for an object. I think having each input follow the exact same structure is much easier to maintain. What are your ideas on implementing this?

2023-02-16 05:48 UTC, jadeallencook commented on src/api/get-requests.ts
> +            )
It looks like you can have a boolean:

<img width="570" alt="Screenshot 2023-02-15 at 9 45 34 PM" src="https://user-images.githubusercontent.com/4443883/219279026-35466e7b-fb87-4e37-b1f2-51e2bda495f5.png">

What seems to be the problem?

If anything, you can push this as is and I can change it.

2023-02-17 00:15 UTC, jadeallencook approved these changes
LGTM 💪

2023-02-17 00:15 UTC, merged