added a user info on the dashboard
jadeallencook/communalists pull request #5
Opened 2022-11-14 00:24 UTC by Ganem1227

2022-11-14 18:04 UTC, jadeallencook requested changes

2022-11-14 18:04 UTC, jadeallencook commented on src/pages/userdata/UserAccountInfo.tsx
> +                <Image src="https://c4.wallpaperflare.com/wallpaper/392/1018/527/flcl-red-background-cat-animals-wallpaper-preview.jpg" rounded fluid height="auto"></Image>
Swap out the source to point to the local.

2022-11-14 18:04 UTC, jadeallencook commented on src/pages/userdata/UserAccountInfo.tsx
> +const DisplayUserInfo = (user) => (
Deconstruct the user here:
`{ name, subjectPronoun }`

2022-11-14 18:04 UTC, jadeallencook commented on src/pages/Dashboard.tsx
> +import UserAccountInfo from './userdata/UserAccountInfo';
This component should live in `components/organisms`.

2022-11-14 18:04 UTC, jadeallencook commented on package.json
> +		"firebase-functions": "^4.0.2",
What are these new packages?

2022-11-14 18:13 UTC, jadeallencook commented on src/pages/userdata/UserAccountInfo.tsx
> +const DisplayUserInfo = (user) => (
Also, please use the `UserInferface` here.

2022-11-20 22:02 UTC, Ganem1227 commented on package.json
> +		"firebase-functions": "^4.0.2",
i'm not sure. I installed the framework and it just added them. I can try removing them and see if something breaks.

2022-11-20 22:17 UTC, Ganem1227 commented on package.json
> +		"firebase-functions": "^4.0.2",
nothing broke

2022-11-22 07:38 UTC, jadeallencook commented
This page was added in the dashboard update.

2022-11-22 07:38 UTC, closed without merging