feat: adding pronouns to aid requests
jadeallencook/communalists pull request #62
Opened 2023-05-14 23:39 UTC by asbhaskar

After this gets merged we can use the same code to add pronouns to the volunteer page

2023-05-17 08:31 UTC, jadeallencook requested changes
Overall this looks great, I'd only suggest using all lowercase for the values. 

```js
{
    he: 'he',
    she: 'she',
    they: 'they',
}

```

We can capitalize the values easily by changing the style, but I think this will be commonly be concatenated within a sentence like this.

```js
`User has invited you to an event that ${subjectProun} is coordinating.`
```

2023-05-17 10:26 UTC, jadeallencook commented
Oh, this is for the requester and not the volunteer. 

In addition to lowercasing the pronouns, please use this the input group in the form:
https://react-bootstrap.github.io/forms/input-group/

2023-05-17 10:28 UTC, jadeallencook commented
We also need to display this information in the request modal used by the volunteer.

2023-05-25 12:51 UTC, asbhaskar commented on src/forms/ViewRequestForm/index.tsx
> +import { Accordion, Button, Form, Modal, Row } from 'react-bootstrap';
I can't find the file but we're not checking of unused variables right now, we should add that to the precommit or eslint config

2023-05-31 05:34 UTC, jadeallencook requested changes
This looks great!

Only suggestion is using the same form group in the request.

<img width="749" alt="Screenshot 2023-05-30 at 10 30 06 PM" src="https://github.com/jadeallencook/communalists/assets/4443883/b8f92f7e-d2af-4b92-a9e4-9edd4a0f4431">

Also, what if someone goes by she/they or he/they?

Is that the same as she/them and he/them?

Edit: I think we should just add "they" to the object pronoun.

2023-05-31 10:24 UTC, asbhaskar commented
I tried searching for how other sites offer this feature, a single dropdown with subj/obj and an extra other option with a conditional text input seems standard. How's that sound?

2023-05-31 22:15 UTC, jadeallencook commented
> I tried searching for how other sites offer this feature, a single dropdown with subj/obj and an extra other option with a conditional text input seems standard. How's that sound?

That'll work, either way!

2023-08-08 18:52 UTC, jadeallencook commented
I'm going to close this out for now but let's revisit this later.

2023-08-08 18:52 UTC, closed without merging